### ISSUE TITLE
Release a new version with the license

### ISSUE THREAD

**Issue by etrejos** [streamich/tree-dump#4]
Could you please release a new version that includes the license addition that happened recently?

This is blocking us from being able to upgrade transitory dependencies in our project.

Related to https://github.com/streamich/tree-dump/issues/3

Thank you!

**Comment by alan-agius4** [comment]
This is also needed by us to make our CI green.

**Comment by anmoser** [comment]
It's also needed by us. Please add license information to npm package. It's still not done.

**Comment by piwysocki** [comment]
Hi @streamich , can you release a new version soon?

**Comment by n-rodriguez** [comment]
ping @streamich

**Comment by Laffery** [comment]
It's also needed to us, our license compilation check failed all the time. Please release a new version with license 🙏

**Comment by streamich** [comment]
finito
